#  https://magicappdev-api.magicappdev.workers.dev
name = "magicappdev-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "e563b0da9d2f6f181f519f78a63e1c94"

[[d1_databases]]
binding = "DB"
database_name = "magicappdev-db"
database_id = "456e0f76-f1f0-44b1-8788-b629a22e39d4" 


[ai]
binding = "AI"

[vars]
ENVIRONMENT = "production"
GITHUB_CLIENT_ID = "Ov23liPcwE31JQjyBQbq"
GITHUB_REDIRECT_URI = "https://magicappdev-api.magicappdev.workers.dev/auth/callback/github"
FRONTEND_URL = "https://app.magicappdev.workers.dev"
MOBILE_REDIRECT_URI = "magicappdev://auth/callback"

[observability]
enabled = true
